graph LR
    Cliente((Cliente))
    Profissional((Profissional))

    subgraph Marketplace [Plataforma de Servicos]
        UC_Busca([Buscar Profissional])
        UC_Filtro([Filtrar Localizacao])
        UC_Pag([Liberar Pagamento])
        UC_Aval([Avaliar Servico])
    end

    Cliente --- UC_Busca
    Cliente --- UC_Pag
    Cliente --- UC_Aval
    
    Profissional --- UC_Pag

    UC_Busca -.->|include| UC_Filtro
    UC_Aval -.->|extend| UC_Pag

    style UC_Aval stroke-dasharray: 5 5
