graph LR
    %% Atores
    C((Cliente))
    CZ((Cozinheiro))
    P[Sistema de Pagamento]

    subgraph Totem [Totem de Autoatendimento]
        A([Fazer Pedido])
        B([Pagar Pedido])
        D([Atualizar Fidelidade])
        E([Monitor Cozinha])
    end

    %% Relacoes
    C --- A
    C --- B
    A -.-> B
    B -.-> D
    B -.-> E

    %% Conexoes Externas
    B --- P
    E --- CZ

    %% Estilo
    style P fill:#f9f,stroke:#333
